# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-16 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
            ],
            options={
                'db_table': 'co_occurrences',
            },
        ),
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'vocabs',
            },
        ),
        migrations.AddField(
            model_name='cooccurrence',
            name='word1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word1', to='expansion.Vocab'),
        ),
        migrations.AddField(
            model_name='cooccurrence',
            name='word2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word2', to='expansion.Vocab'),
        ),
    ]
