# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-14 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordCount', models.IntegerField()),
                ('rhyme_pinyin', models.CharField(max_length=30)),
                ('rhyme_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.Template')),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.Verse'),
        ),
    ]
